---
  deployment:
      tasks:
        - export DEPLOYPATH=/home/kabiljbe/public_html/
        - /bin/cp * $DEPLOYPATH
        - /bin cp * $DEPLOYPATH 
        - /bin cp /fr/* $DEPLOYPATH
        - /bin cp /en/* $DEPLOYPATH